#### general settings
name: Corrupted_noise
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
compression_quality: -1

#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    aug: noise
    noise_data: ../datasets/DF2K/Corrupted_noise/
    dataroot_GT: ../datasets/DF2K/generated/tdsr/HR
    dataroot_LQ: ../datasets/DF2K/generated/tdsr/LR
    use_shuffle: true
    n_workers: 32  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val
    mode: LQGT
    dataroot_GT: ../datasets/Corrupted-va-y
    dataroot_LQ: ../datasets/Corrupted-va-x

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ../pretrained_model/DF2K_JPEG.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-6
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 0
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 5000001
  warmup_iter: -1  # no warm up
  lr_steps: [10000, 50000, 100000, 500000]
  lr_gamma: 0.5

  pixel_criterion: l2
  pixel_weight: !!float 1
  feature_criterion: l1
  feature_weight: !!float 5e-2
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 0

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
